# Generated by Django 4.0.1 on 2022-01-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allitems',
            name='Image',
            field=models.FileField(default='Images/default.jpg', upload_to='Images'),
        ),
    ]
