# Generated by Django 4.0.1 on 2022-01-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_allitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.FileField(default='Images/default.jpg', upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='Image',
            field=models.FileField(default='Images/default.jpg', upload_to='Images'),
        ),
    ]
