# Generated by Django 4.0.1 on 2022-01-31 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_category_image_alter_meals_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
